export const account = {
	_resource: "studio/accounts",
	_resource_std: "studio/accounts/standard",
	_resource_multi: "studio/accounts/multichannel",
	ViewBots: "ViewBots",
	CreateAccount: "CreateAccount",
	UpdateAccount: "UpdateAccount",
	CreateMultichannelAccount: "CreateMultichannelAccount",
};
export const training = {
	_resource: "studio/training",
	ViewTopics: "ViewTopics",
	DeployAIStage: "DeployAIStage",
	DeployAIProduction: "DeployAIProduction",
	CreateCategory: "CreateCategory",
	CreateTopic: "CreateTopic",
	DeployTopic: "DeployTopic",
	DeleteTopic: "DeleteTopic",
	CreateResponse: "CreateResponse",
	UpdateResponse: "UpdateResponse",
	DeleteResponse: "DeleteResponse",
	ExportResponse: "ExportResponse",
	UpdateSamples: "UpdateSamples",
	UpdateCategory: "UpdateCategory",
	UpdateTopic: "UpdateTopic",
	ViewSubworkflow: "ViewSubworkflow",
	CreateSubworkflow: "CreateSubworkflow",
	UpdateSubworkflowTitle: "UpdateSubworkflowTitle",
	UpdateLanguageVariant: "UpdateLanguageVariant",
	ExportSubworkflow: "ExportSubworkflow",
	CloneSubworkflow: "CloneSubworkflow",
	DeleteSubworkflow: "DeleteSubworkflow",
	ViewEntities: "ViewEntities",
	ArchiveEntity: "ArchiveEntity",
	CreateValue: "CreateValue",
	UpdateEntity: "UpdateEntity",
	ViewAnswerNet: "ViewAnswerNet",
	UpdateToDraft: "UpdateToDraft",
	DeleteAnswerNetQuestion: "DeleteAnswerNetQuestion",
	SettingsKnowledge: "SettingsKnowledge",
	DownloadAnswerNetReport: "DownloadAnswerNetReport",
	CreateCuratedFAQs: "CreateCuratedFAQs",
};
export const analytics = {
	_resource: "studio/analytics",
	DownloadReport: "DownloadReport",
};
export const optimize = {
	_resource: "studio/optimize",
	UpdateRecommendations: "UpdateRecommendations",
	Download: "Download",
	CreateTopic: "CreateTopic",
	UpdateScope: "UpdateScope",
	UpdateHideShowToggle: "UpdateHideShowToggle",
};
export const discover = {
	_resource: "studio/discover",
	ViewDiscover: "ViewDiscover",
	UploadData: "UploadData",
};
export const queryViewer = {
	_resource: "studio/query-viewer",
	ViewQueryAnalyzer: "ViewQueryAnalyzer",
};
export const conversationViewer = {
	_resource: "studio/conversation-viewer",
	ViewConversation: "ViewConversation",
};
export const integrationBuilder = {
	_resource: "studio/integration-builder",
	ViewIntegrationBuilder: "ViewIntegrationBuilder",
	ImportRecipe: "ImportRecipe",
	CreateRecipe: "CreateRecipe",
	UpdateRecipe: "UpdateRecipe",
	ExportRecipe: "ExportRecipe",
	DeleteRecipe: "DeleteRecipe",
	CreateTag: "CreateTag",
	UpdateTag: "UpdateTag",
	DeleteTag: "DeleteTag",
	CreateConnection: "CreateConnection",
	UpdateConnection: "UpdateConnection",
	DeleteConnection: "DeleteConnection",
	CreateLookup: "CreateLookup",
	UpdateLookup: "UpdateLookup",
	UpdateAllEntries: "UpdateAllEntries",
	ImportEntries: "ImportEntries",
	CreateLookupTableEntry: "CreateLookupTableEntry",
	UpdateLookupTableEntry: "UpdateLookupTableEntry",
	DeleteLookupTableEntry: "DeleteLookupTableEntry",
};
export const settings = {
	_resource: "studio/settings",
	ViewAIAgent: "ViewAIAgent",
	UpdateAIProfile: "UpdateAIProfile",
	CreateResponseField: "CreateResponseField",
	UpdateResponseField: "UpdateResponseField",
	DeleteResponseField: "DeleteResponseField",
	ViewKnowledge: "ViewKnowledge",
	CreateKnowledgeSources: "CreateKnowledgeSources",
	UpdateKnowledgeSources: "UpdateKnowledgeSources",
	DeleteKnowledgeSources: "DeleteKnowledgeSources",
	DownloadKnolwedgeSource: "DownloadKnolwedgeSource",
	ViewGenerativeAI: "ViewGenerativeAI",
	ViewUsers: "ViewUsers",
	CreateUser: "CreateUser",
	UpdateUser: "UpdateUser",
	DeleteUser: "DeleteUser",
	ViewIntegrations: "ViewIntegrations",
	ViewWWEmbedScript: "ViewWWEmbedScript",
	ViewWWConfigureAppearance: "ViewWWConfigureAppearance",
	DeployWWToStage: "DeployWWToStage",
	DeployWWToProd: "DeployWWToProd",
	ViewWWSecurity: "ViewWWSecurity",
	ViewWWFileSharing: "ViewWWFileSharing",
	ViewWWJson: "ViewWWJson",
	UpdateJson: "UpdateJson",
	ViewWWAuthenticate: "ViewWWAuthenticate",
	CreateWWAuthentication: "CreateWWAuthentication",
	CreateWWAPIKey: "CreateWWAPIKey",
	UpdateKnowledgeBase: "UpdateKnowledgeBase",
	ViewIntegrationKBSources: "ViewIntegrationKBSources",
	UpdateIntegrationKBSource: "UpdateIntegrationKBSource",
	ViewIntegrationKBResponseSettings: "ViewIntegrationKBResponseSettings",
	UpdateIntegrationKBResponseSettings: "UpdateIntegrationKBResponseSettings",
	ViewAnswerNet: "ViewAnswerNet",
	UpdateAnswerNetSetup: "UpdateAnswerNetSetup",
	DeployAnswerNetToProd: "DeployAnswerNetToProd",
	CreateAnswerNetQA: "CreateAnswerNetQA",
	UpdateAnswerNetConfig: "UpdateAnswerNetConfig",
	ViewChatWidget: "ViewChatWidget",
	ViewChatWidgetJSON: "ViewChatWidgetJSON",
	DeployCWSettingsToProd: "DeployCWSettingsToProd",
	UpdateCWSettings: "UpdateCWSettings",
	DeployCWJsonToProd: "DeployCWJsonToProd",
	UpdateCWJson: "UpdateCWJson",
	CreateCWJWTKeyStaging: "CreateCWJWTKeyStaging",
	CreateCWJWTKeyProd: "CreateCWJWTKeyProd",
	UpdateCWSecurityDomainStaging: "UpdateCWSecurityDomainStaging",
	UpdateCWSecurityDomainProd: "UpdateCWSecurityDomainProd",
	ViewLanguage: "ViewLanguage",
	CreateLanguage: "CreateLanguage",
	UpdateLanguage: "UpdateLanguage",
	DeleteLanguage: "DeleteLanguage",
	DeployLanguage: "DeployLanguage",
	ViewConverstaionOS: "ViewConverstaionOS",
	UpdateConversationOS: "UpdateConversationOS",
	DeployConversationOSToProd: "DeployConversationOSToProd",
	ViewPreferences: "ViewPreferences",
	CreatePreferencesConfig: "CreatePreferencesConfig",
	UpdatePreferencesConfig: "UpdatePreferencesConfig",
	DeletePreferencesConfig: "DeletePreferencesConfig",
	ViewFeedback: "ViewFeedback",
	DeployFeedbackReviewToProd: "DeployFeedbackReviewToProd",
	UpdateFeedbackReview: "UpdateFeedbackReview",
	DeployFeedbackSurveyToProd: "DeployFeedbackSurveyToProd",
	UpdateFeedbackSurvey: "UpdateFeedbackSurvey",
	ViewCustomDashBoards: "ViewCustomDashBoards",
	ViewHumanAgents: "ViewHumanAgents",
	CreateCustomDashBoards: "CreateCustomDashBoards",
	CreateHumanAgents: "CreateHumanAgents",
	UpdatePersonalProfile: "UpdatePersonalProfile",
	CreateGenerativeAiModel: "CreateGenerativeAiModel",
	UpdateConversationOsToggle: "UpdateConversationOsToggle",
	UpdateConversationOsAccordionToggle: "UpdateConversationOsAccordionToggle",
	UpdateReviewAccordionToggle: "UpdateReviewAccordionToggle",
	UpdateAnswerAiToggle: "UpdateAnswerAiToggle",
	UpdateAnswerGptToggle: "UpdateAnswerGptToggle",
	UpdateStaticOptionToggle: "UpdateStaticOptionToggle",
	UpdateUploadFile: "UpdateUploadFile",
	UpdateUploadInterface: "UpdateUploadInterface",
	UpdateUploadList: "UpdateUploadList",
	UpdateDownloadSampleFile: "UpdateDownloadSampleFile",
	UpdateSummarization: "UpdateSummarization",
	UpdateGenerativeAI: "UpdateGenerativeAI",
	UpdateAnswerNetFooter: "UpdateAnswerNetFooter",
	UpdateConversationOsFooter: "UpdateConversationOsFooter",
	CreateDataExportSchedule: "CreateDataExportSchedule",
	UpdateBrandTone: "UpdateBrandTone",
	UpdateCustomFields: "UpdateCustomFields",
	UpdateIntegration: "UpdateIntegration",
	CreateIntegration: "CreateIntegration",
	DeleteAgentAssist: "DeleteAgentAssists",
	UpdateAgentAssist: "UpdateAgentAssist",
	DeployAgentAssist: "DeployAgentAssist",
};
export const aiUser = {
	_resource: "studio/ai-user",
	UpdateUserProfile: "UpdateUserProfile",
	CreateUser: "CreateUser",
	UpdateUserAgent: "UpdateUserAgent",
	UpdateAgentRole: "UpdateAgentRole",
};
